package com.example.PetstoreApplication.controllers.api;

import com.example.PetstoreApplication.models.Product;
import com.example.PetstoreApplication.repositories.ProductRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Optional;

/* @Controller + @RestBody (@RestBody - аннотация для апи:
сообщаем спрингу, что не будем использовать html-шаблоны) */
@RestController
@RequestMapping("/api")
public class ApiController {
  private final ProductRepository productRepository;
  @Autowired
  public ApiController(ProductRepository productRepository) {
    this.productRepository = productRepository;
  }

  // http://localhost:8080/api/info
  @GetMapping("/info")
  public String getInfoApi ()
  {
    return "Данное API предназначено для работы с товарами";
  }

  @GetMapping("/products")
  public List<Product> getAllProducts()
  {
    // здесь с помощью либы Jackson конвертируем эти объекты в JSON
    return productRepository.findAll();
  }

  @GetMapping("/product/search/{id}")
  public Optional<Product> getProductById(@PathVariable("id") Long id)
  {
    return productRepository.findById(id);
  }

  @GetMapping("/product/delete/{id}")
  public String deleteProductId(@PathVariable("id") Long id)
  {
    productRepository.deleteById(id);
    return "товар успешно удален";
  }

  //http://localhost:8080/api/product/add/?name=Стул&price=4750
  @GetMapping("/product/add")
  public String addProduct(@RequestParam("name") String name, @RequestParam(
          "price") float price)
  {
    Product newProduct = new Product();
    productRepository.save(newProduct);
    return "Товар добавлен";
  }

}

/*  create table product(
          id int primary key generated by default as identity,
          name varchar(100) not null,
  price float not null
          );
insert into product(name, price)
VALUES('стол', 1000), ('стул', 2500); */